<?php
class AdminProductsController  extends AdminProductsControllerCore{
    public function postProcess()
    {
        // Catch the value from post param here and save it on product

        parent::postProcess(); // TODO: Change the autogenerated stub
    }
}
